#ifndef GAMEATTRIBUTES_H
#define GAMEATTRIBUTES_H

#ifndef RABBITM_HEALTH
//Living objects

//Rabbits
//Rabbit Male
#define RABBITM_HEALTH 25
#define RABBITM_MVSPEED 5
#define RABBITM_ATTACK 7
#define RABBITM_ARMOR 2
#define RABBITM_ATTSPEED 2
#define RABBITM_GATHSPEED 4
#define RABBITM_BLDSPEED 5
#define RABBITM_HEALSPEED 0

//Rabbit Female
#define RABBITF_HEALTH 20
#define RABBITF_MVSPEED 6
#define RABBITF_ATTACK 5
#define RABBITF_ARMOR 1
#define RABBITF_ATTSPEED 2
#define RABBITF_GATHSPEED 1
#define RABBITF_BLDSPEED 2
#define RABBITF_HEALSPEED 0
#define RABBITF_OVULSPEED 5
#define RABBITF_OVULLENGTH 60
#define RABBITF_BIRTHSPEED 20


//Rabbit Kid
#define RABBITK_HEALTH 10
#define RABBITK_MVSPEED 4
#define RABBITK_ATTACK 0
#define RABBITK_ARMOR 0
#define RABBITK_ATTSPEED 0
#define RABBITK_GATHSPEED 0
#define RABBITK_BLDSPEED 0
#define RABBITK_HEALSPEED 2
#define RABBITK_GROWSPEED 3

//Rabbit-increasing attributes
#define RABBIT_INCR_ATT1 2
#define RABBIT_INCR_ATT2 3
#define RABBITALL_INCR_ARM1 2
#define RABBITALL_INCR_ARM2 3
#define RABBIT_INCR_HLTH1 10
#define RABBIT_INCR_HLTH1 20
#define RABBITK_INCR_HLTH1 5
#define RABBITK_INCR_HLTH2 10
#define RABBITALL_INCR_MVSPEED1 1
#define RABBITALL_INCR_MVSPEED2 2
#define RABBIT_INCR_ATTSPEED1 1
#define RABBIT_INCR_ATTSPEED2 1
#define RABBIT_INCR_GATHSPEED1 1
#define RABBIT_INCR_GATHSPEED2 1
#define RABBIT_INCR_BLDSPEED1 1
#define RABBIT_INCR_BLDSPEED2 1
#define RABBITALL_INCR_HEALSPEED1 1
#define RABBITALL_INCR_HEALSPEED2 2
#define RABBIT_INCR_GROWSPEED1 1
#define RABBIT_INCR_GROWSPEED1 2
#define RABBIT_INCR_OVULSPEED1 1
#define RABBIT_INCR_OVULSPEED2 2
#define RABBIT_INCR_BIRTHSPEED1 1
#define RABBIT_INCR_BIRTHSPEED2 1
#define RABBIT_INCR_OVULLENGTH -1
#define RABBIT_INCR_OVULLENGTH -2

#endif
#endif